### ISSUE TITLE
TypeError: IntervenableModel.train() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by danikhan632** [stanfordnlp/pyreft#31]
This occurs when copying the exact alpaca train cmd given on a new conda env, unsure why

```bash
Traceback (most recent call last):
  File "/home/green/code/nlp/pyreft/examples/alpaca/train.py", line 128, in <module>
    train()
  File "/home/green/code/nlp/pyreft/examples/alpaca/train.py", line 122, in train
    trainer.train()
  File "/home/green/miniconda3/envs/reft/lib/python3.11/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/green/miniconda3/envs/reft/lib/python3.11/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/green/miniconda3/envs/reft/lib/python3.11/site-packages/transformers/trainer.py", line 3028, in training_step
    model.train()
  File "/home/green/miniconda3/envs/reft/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2430, in train
    module.train(mode)
TypeError: IntervenableModel.train() takes 1 positional argument but 2 were given

```

**Comment by frankaging** [comment]
hey! could you try:
- python >=3.8, since pyvene requires that.
- `pip install -r requirements.txt` to make sure versions of other libs are correct?
Thanks!

**Comment by danikhan632** [comment]
I fixed it by running 'export CUDA_VISIBLE_DEVICES=0' so looks like multi GPU is causing issues. 

Also had a few question I wanted to ask, my discord is @danikhan632

**Comment by frankaging** [comment]
you are right! remembering this now. we will support multi-gpu, sharding etc.. soon. working on it.

**Comment by frankaging** [comment]
closing this for now, tracking multi-gpu support here: https://github.com/stanfordnlp/pyreft/issues/25
