### ISSUE TITLE
[P1] Cannot reproduce instruction training

### ISSUE THREAD

**Issue by konstantina-ellalab** [stanfordnlp/pyreft#50]
Hey, I am trying to reproduce the instruction training mentioned in the README that takes 18 minutes and uses the ultrafeedback dataset.

I executed this command as suggested:

```bash
python train.py -task ultrafeedback \
-data_dir <your_dataset_folder_path> \
-model meta-llama/Llama-2-7b-hf \
-seed 44 -l 3;9;18;24 -r 4 -p f5+l5 -e 9 -lr 9e-4 \
-type LoreftIntervention \
-gradient_accumulation_steps 32 \
-batch_size 4 \
-eval_batch_size 2 \
--test_split test \
--use_normalized_template \
--max_length 768
```

I removed the `data_dir` parameter since I do not have any relevant dataset locally and added `--output_dir my_dir` for saving the output. The error that I got from running the script is that the ultrafeedback dataset could not be found in Huggingface. To fix this, I changed the task config by adding `openbmb/UltraFeedback`:

```
"ultrafeedback": {
        "train_datasets": ["openbmb/UltraFeedback"],
        "eval_datasets": ["alpaca_eval"],
        "task_prompt_template": alpaca_prompt_template,
        "trigger_tokens": "### Response:",
        "generation_args": {
            # align with https://arxiv.org/abs/2402.15179
            True: {
                "max_length": 2048,
                "do_sample": False,
            },
            False: {
                "max_length": 2048,
                "no_repeat_ngram_size": 5,
                "repetition_penalty": 1.1,
                "do_sample": False,
            }
        }
    },
 ```
 The command went through, the data was downloaded, but then there is an error while building the `base_input`:
 
```
 
Traceback (most recent call last):
  File "/home/konstantina/loreft/train.py", line 460, in <module>
    main()
  File "/home/konstantina/loreft/train.py", line 456, in main
    finetune(**vars(args), args=args)
  File "/home/konstantina/loreft/train.py", line 165, in finetune
    train_dataset = ReftDataset(
  File "/home/konstantina/loreft/dataset.py", line 181, in __init__
    base_input = base_prompt + data_item["output"] + tokenizer.eos_token
KeyError: 'output'
9: command not found
18: command not found
24: command not found
```
 The `dataset.py` in the error stack refers to the code in the `loreft` directory in the examples.
 
Also, I basically have the same issue when I try to run the `instruct` experiment. Even though the README says that everything is done via Huggingface, I get this error:

`datasets.exceptions.DatasetNotFoundError: Dataset 'instruct' doesn't exist on the Hub or cannot be accessed`

when I run

```bash
python train.py -task instruct \
-model meta-llama/Llama-2-7b-hf \
-seed 44 -l 3;9;18;24 -r 4 -p f5+l5 -e 9 -lr 9e-4 \
-type LoreftIntervention \
-gradient_accumulation_steps 32 \
-batch_size 4 \
-eval_batch_size 2 \
--test_split test \
--use_normalized_template \
--max_length 768
--output_dir my_dir
```

**Comment by frankaging** [comment]
@konstantina-ellalab thanks for raising the issue! we updated the folder README to have clearer instructions. Please take a look:
https://github.com/stanfordnlp/pyreft/tree/main/examples/loreft

There are **two changes** needed based on your logs above:

1. You need to download our parsed version of `UltraFeedback` to avoid writing your own dataloader. The reason is that `UltraFeedback` is a pair-wise preference dataset, and we need to preprocess it to make it a SFT dataset.

**To download our datasets, run this command inside our `loreft` folder**:
```bash
bash load_datasets.sh
````

2. When you run the command, **make sure you escape the string** after `-l 3;9;18;24`. We need to provide as `-l "3;9;18;24"` otherwise `;` is considered as a line-break which breaks the command.

We updated our README now to have this escape. You can run like:
```bash
python train.py -task ultrafeedback \
-data_dir dataset \
-model meta-llama/Llama-2-7b-hf \
-seed 42 -l "3;9;18;24" -r 4 -p f5+l5 -e 9 -lr 9e-4 \
-type LoreftIntervention \
-gradient_accumulation_steps 32 \
-batch_size 4 \
-eval_batch_size 2 \
--test_split test \
--use_normalized_template \
--max_length 768
```

Finally, to have that 18min run-time, you need to train with downsampled training data with 1K examples as stated in the paper and in the README. To do this, you want to provide this extra argument: `--max_n_train_example 1000`.

Let me know if you have other questions!

**Comment by frankaging** [comment]
lowering the priority to P1 as I don't think any code change is needed. data loading script as well as README are updated.

**Comment by frankaging** [comment]
@konstantina-ellalab hey, just want to follow up here. is the issue fixed by now? let me know if there are other issues! Thanks.

**Comment by konstantina-ellalab** [comment]
@frankaging thank you for the quick feedback and the fixes! I have not tested the solution yet, but I will do that soon and let you know here how it goes.

**Comment by konstantina-ellalab** [comment]
Hey @frankaging , thank you for the updated process. It worked, but there was a small issue that I resolved on my side. The ultrafeedback dataset was too big and it was not downloaded automatically with `git clone`, nor with `wget`, so I downloaded it and added it manually to the remote machine I am using. 
Afterwards, the `train.py` worked until I got an error about wrong arguments:

```
nohup: ignoring input
task: ultrafeedback, model: meta-llama/Llama-2-7b-hf, intervention_type: LoreftIntervention, layers: 3;9;18;24, rank: 4, position: f5+l5, epoch: 9, train_on_inputs: False, max_length: 768, allow_cls_grad: False
loading data for dataset:  dataset/ultrafeedback

Generating train split: 0 examples [00:00, ? examples/s]
Generating train split: 29970 examples [00:00, 231082.00 examples/s]
Generating train split: 62135 examples [00:00, 271694.35 examples/s]
Generating train split: 62135 examples [00:03, 17780.39 examples/s] 

  0%|          | 0/1000 [00:00<?, ?it/s]
  0%|          | 1/1000 [00:01<18:20,  1.10s/it]
  1%|          | 12/1000 [00:01<01:14, 13.32it/s]
  2%|▏         | 21/1000 [00:01<00:41, 23.86it/s]
  3%|▎         | 32/1000 [00:01<00:25, 37.84it/s]
  5%|▍         | 46/1000 [00:01<00:16, 56.88it/s]
  6%|▌         | 57/1000 [00:01<00:14, 66.05it/s]
  
  ..........
  
100%|██████████| 1000/1000 [00:07<00:00, 132.00it/s]


Downloading builder script:   0%|          | 0.00/8.10k [00:00<?, ?B/s]
Downloading builder script: 100%|██████████| 8.10k/8.10k [00:00<00:00, 23.1MB/s]

Downloading readme:   0%|          | 0.00/30.0 [00:00<?, ?B/s]
Downloading readme: 100%|██████████| 30.0/30.0 [00:00<00:00, 209kB/s]

Downloading data:   0%|          | 0.00/621k [00:00<?, ?B/s]
Downloading data: 100%|██████████| 621k/621k [00:00<00:00, 11.3MB/s]
/home/konstantina/.cache/huggingface/datasets/downloads/07bde58ae497102ab81d326d84eafcf6c2c7e8df8cd8b8d0ef64d9eceab41ada

Generating eval split: 0 examples [00:00, ? examples/s]
Generating eval split: 805 examples [00:00, 6155.66 examples/s]

  0%|          | 0/805 [00:00<?, ?it/s]
 20%|██        | 163/805 [00:00<00:00, 1623.85it/s]
 40%|████      | 326/805 [00:00<00:00, 1554.55it/s]
 60%|█████▉    | 482/805 [00:00<00:00, 1555.57it/s]
 79%|███████▉  | 638/805 [00:00<00:00, 1426.00it/s]
 97%|█████████▋| 782/805 [00:00<00:00, 1428.49it/s]
100%|██████████| 805/805 [00:00<00:00, 1475.16it/s]

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]
config.json: 100%|██████████| 609/609 [00:00<00:00, 3.05MB/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]
model.safetensors.index.json: 100%|██████████| 26.8k/26.8k [00:00<00:00, 62.7MB/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s][A

model-00001-of-00002.safetensors:   0%|          | 10.5M/9.98G [00:00<02:02, 81.1MB/s][A

model-00001-of-00002.safetensors:   0%|          | 21.0M/9.98G [00:00<01:52, 88.6MB/s][A

model-00001-of-00002.safetensors:   0%|          | 31.5M/9.98G [00:00<01:52, 88.1MB/s][A

............


model-00001-of-00002.safetensors: 100%|██████████| 9.98G/9.98G [01:58<00:00, 117MB/s][A
model-00001-of-00002.safetensors: 100%|██████████| 9.98G/9.98G [01:58<00:00, 84.3MB/s]

Downloading shards:  50%|█████     | 1/2 [02:42<02:42, 162.99s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s][A

model-00002-of-00002.safetensors:   0%|          | 10.5M/3.50G [00:00<01:31, 38.3MB/s][A

model-00002-of-00002.safetensors:   1%|          | 21.0M/3.50G [00:00<01:01, 56.8MB/s][A

.............


model-00002-of-00002.safetensors: 100%|██████████| 3.50G/3.50G [00:54<00:00, 62.7MB/s][A
model-00002-of-00002.safetensors: 100%|██████████| 3.50G/3.50G [00:54<00:00, 64.1MB/s]

Downloading shards: 100%|██████████| 2/2 [03:51<00:00, 107.70s/it]
Downloading shards: 100%|██████████| 2/2 [03:51<00:00, 115.99s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [01:39<01:39, 99.28s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [02:11<00:00, 60.08s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [02:11<00:00, 65.96s/it]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]
generation_config.json: 100%|██████████| 188/188 [00:00<00:00, 1.04MB/s]

trainable intervention params: 262,176 || trainable model params: 0
model params: 6,738,415,616 || trainable%: 0.003890766241510503

  0%|          | 0/27 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/konstantina/projects/loreft/train.py", line 460, in <module>
    main()
  File "/home/konstantina/projects/loreft/train.py", line 456, in main
    finetune(**vars(args), args=args)
  File "/home/konstantina/projects/loreft/train.py", line 356, in finetune
    trainer.train()
  File "/home/konstantina/miniconda3/envs/pyreft_test/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/home/konstantina/miniconda3/envs/pyreft_test/lib/python3.10/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/konstantina/miniconda3/envs/pyreft_test/lib/python3.10/site-packages/transformers/trainer.py", line 3028, in training_step
    model.train()
  File "/home/konstantina/miniconda3/envs/pyreft_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2394, in train
    module.train(mode)
TypeError: IntervenableModel.train() takes 1 positional argument but 2 were given

  0%|          | 0/27 [00:00<?, ?it/s]

```

This was my command:

```
python loreft/train.py -task ultrafeedback -data_dir loreft/dataset -model meta-llama/Llama-2-7b-hf -seed 42 -l "3;9;18;24" -r 4 -p f5+l5 -e 9 -lr 9e-4 -type LoreftIntervention -gradient_accumulation_steps 32 -batch_size 4 -eval_batch_size 2 --test_split test --use_normalized_template --max_length 768 --output_dir loreft/ --max_n_train_example 1000

```

**Comment by frankaging** [comment]
@konstantina-ellalab Thanks for the update!

As noted in our updated README: 
https://github.com/stanfordnlp/pyreft?tab=readme-ov-file#quickstart

You need to add `CUDA_VISIBLE_DEVICES=0` before your command to make sure you are running with a single GPU. We currently only support a single GPU case, and are working on multi-GPU support.

**Comment by konstantina-ellalab** [comment]
@frankaging Thanks for the suggestion. I am setting this environment variable in advance and the training works now. It took approximately 2 hours. However, the model is not saved by default. I only see two json files with evaluation results and another json file with the training config. I am training again now with the `-save_model` parameter and hope to be able to run inference on the saved model later on.

Could you please share a code snippet that I could use to do inference with the trained model? The instructions in the repo are updated and I am not sure what the most up-to-date inference code is at the moment. Here is what I have so far:

```
prompt_no_input_template = """Below is an instruction that \
describes a task. Write a response that appropriately \
completes the request.

### Instruction:
%s

### Response:
"""

device = "cuda" if torch.cuda.is_available() else "cpu"

model_name_or_path = ""
reft_model_name_or_path = ""

tokenizer = transformers.AutoTokenizer.from_pretrained(
    model_name_or_path, model_max_length=2048, padding_side="right", use_fast=False)
tokenizer.pad_token = tokenizer.unk_token
model = transformers.AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.bfloat16, device_map=device)

reft_model = ReftModel.load(reft_model_name_or_path, model)
reft_model.set_device(device)

instruction = "Tell me about the NLP Group at Stanford University."

# tokenize and prepare the input
prompt = prompt_no_input_template % instruction
prompt = tokenizer(prompt, return_tensors="pt").to(device)

intervention_locations = torch.tensor([get_intervention_locations(
    last_position=prompt["input_ids"].shape[-1], positions="f5+l5",
    num_interventions=len(reft_model.interventions))]).permute(1, 0, 2).tolist()

# generate
_, reft_response = reft_model.generate(
    prompt, 
    unit_locations={"sources->base": (None, intervention_locations)},
    intervene_on_prompt=True, max_new_tokens=512, do_sample=False, 
    no_repeat_ngram_size=5, repetition_penalty=1.1,
    eos_token_id=tokenizer.eos_token_id, early_stopping=True
)
print(tokenizer.decode(reft_response[0], skip_special_tokens=True))
```

**Comment by konstantina-ellalab** [comment]
@frankaging The current issue is that I am not sure how to load a reft model from the local directory. I can see that the representations are saved in bin files and I am trying to follow the main demo to load them. However, the demo assumes the reft_model is in memory already, so not sure how to combine the base model with the reft training output to create a reft_model and then use it for generation.

```

import torch
import transformers
import pyreft
import torch, transformers
from pyreft import (
    ReftModel
)

model_name_or_path = "yahma/llama-7b-hf"
reft_model_name_or_path = "Llama-2-7b-hf.ultrafeedback.20240419104401887890/"

prompt_no_input_template = """<s>[INST] <<SYS>>
You are a helpful assistant.
<</SYS>>

%s [/INST]
"""

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name_or_path, torch_dtype=torch.bfloat16, device_map="cuda")

# get tokenizer
tokenizer = transformers.AutoTokenizer.from_pretrained(
    model_name_or_path, model_max_length=2048, 
    padding_side="right", use_fast=False)
tokenizer.pad_token = tokenizer.unk_token

# This works but the local directory is not used

reft_config = pyreft.ReftConfig(representations={
    "layer": 15, "component": "block_output",
    "low_rank_dimension": 4,
    "intervention": pyreft.LoreftIntervention(embed_dim=model.config.hidden_size,
    low_rank_dimension=4)})

reft_model = pyreft.get_reft_model(model, reft_config)

# This gives an error:

# ValueError: RepresentationConfig(layer=3, component='block_output', unit='pos', max_number_of_units=1, low_rank_dimension=4, intervention_type=None, intervention=None, subspace_partition=None, group_key=None, intervention_link_key=None, moe_key=None, source_representation=None, hidden_source_representation=None) format in our representation list is not supported.

reft_model = ReftModel(reft_config, model)
reft_model.load(load_directory=reft_model_name_or_path, model=model)
```

**Comment by konstantina-ellalab** [comment]
@frankaging thank you for the code and sorry for the late reply. I am not able to test this at the moment, but it looks good, so I will close the ticket and come back if necessary. Thanks!
