### ISSUE TITLE
[P1] Error running new example code

### ISSUE THREAD

**Issue by dyahadila** [stanfordnlp/pyreft#58]
Hello,

i get the following error when trying to run the new example code:

```Traceback (most recent call last):
  File "/home/ubuntu/self-alignment/ReFT/reft_example.py", line 65, in <module>
    _ = trainer.train()
  File "/opt/conda/envs/reft_clean/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/opt/conda/envs/reft_clean/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/envs/reft_clean/lib/python3.10/site-packages/transformers/trainer.py", line 3130, in training_step
    model.train()
  File "/opt/conda/envs/reft_clean/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2394, in train
    module.train(mode)
TypeError: IntervenableModel.train() takes 1 positional argument but 2 were given
```

Any help on how to fix this is greatly appreciated!

**Comment by frankaging** [comment]
hey! thanks for the question.

<img width="843" alt="Screenshot 2024-04-19 at 1 55 15 PM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/8a99e9bd-00d4-4bc4-b01c-29b860aa562b">

**Note that ReFT only supports a single GPU for now - make sure you set CUDA_VISIBLE_DEVICES=0 or something equivalent! We are working on supporting multi-GPU right now.**

We are working on multi-GPU support currently. For now, you have to setup the env variable for a single GPU.

**Comment by frankaging** [comment]
closing this issue for now --- feel free to reopen if the problem still exists.
